/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'vlinetskyi' at '3/8/17 3:29 PM' with Gradle 2.14.1
 *
 * @author vlinetskyi, @date 3/8/17 3:29 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
